global-variables:
  - &clone
    name: clone
    image: alpine/git
    commands:
    - git clone -b "$DRONE_BRANCH" "$DRONE_REMOTE_URL" .

kind: pipeline
type: kubernetes
name: release

clone:
  disable: true

steps:
  - <<: *clone

trigger:
  branch:
  - release/*
  event:
  - push
